sudo: false
# This repository doesn't contain Python code, but it uses Python tooling.
language: python
python:
  - "2.7"
install:
  - git clone https://github.com/tabatkins/bikeshed.git
  - pip install --editable $PWD/bikeshed
  - bikeshed update
script:
  - bikeshed spec
notifications:
  email: false
